/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TruthTable;

import java.awt.Toolkit;

/**
 *
 * @author asus
 */
public class Difficulty extends javax.swing.JFrame {

    /**
     * Creates new form Difficulty
     */
    public Difficulty() {
        initComponents();
        setIcon();
    }

    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gamelogo.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        java.awt.Button button1 = new java.awt.Button();
        javax.swing.JLabel r3 = new javax.swing.JLabel();
        javax.swing.JLabel q3 = new javax.swing.JLabel();
        javax.swing.JLabel q1 = new javax.swing.JLabel();
        javax.swing.JLabel r2 = new javax.swing.JLabel();
        javax.swing.JLabel s3 = new javax.swing.JLabel();
        javax.swing.JLabel q2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel p2 = new javax.swing.JLabel();
        javax.swing.JLabel p1 = new javax.swing.JLabel();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        javax.swing.JButton jButton2 = new javax.swing.JButton();
        javax.swing.JButton jButton3 = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Truth Runes");
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);
        setSize(new java.awt.Dimension(1336, 720));

        jPanel1.setBackground(new java.awt.Color(23, 24, 22));
        jPanel1.setMaximumSize(new java.awt.Dimension(1336, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1336, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1336, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setBackground(new java.awt.Color(51, 51, 51));
        button1.setFont(new java.awt.Font("Æ Systematic TT BRK", 1, 24)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("<");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 55, 60));

        r3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/red-R.gif"))); // NOI18N
        jPanel1.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 510, 110, 560));

        q3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/letter-q.gif"))); // NOI18N
        jPanel1.add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 470, 100, 720));

        q1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/letter-q.gif"))); // NOI18N
        jPanel1.add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 90, 640));

        r2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/red-R.gif"))); // NOI18N
        jPanel1.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 110, 560));

        s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/white-S.gif"))); // NOI18N
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 510, 120, 560));

        q2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/letter-q.gif"))); // NOI18N
        jPanel1.add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 100, 720));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/invi-P.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 120, 550));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/invi-P.gif"))); // NOI18N
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 120, 550));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/invi-P.gif"))); // NOI18N
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 160, 550));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Alkhemikal", 0, 50)); // NOI18N
        jButton1.setText("EASY");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, 190));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Alkhemikal", 0, 50)); // NOI18N
        jButton2.setText("MEDIUM");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 330, 190));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Alkhemikal", 0, 50)); // NOI18N
        jButton3.setText("HARD");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, 330, 190));

        jLabel1.setFont(new java.awt.Font("Alkhemikal", 0, 140)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Difficulty");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 920, 130));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/bg4.gif"))); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(1336, 720));
        bg.setMinimumSize(new java.awt.Dimension(1336, 720));
        bg.setPreferredSize(new java.awt.Dimension(1336, 720));
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Easy().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Medium().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Hard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Difficulty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

