/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TruthTable;

import java.awt.Toolkit;

/**
 *
 * @author asus
 */

public class LoadingScreen extends javax.swing.JFrame {

    /**
     * Creates new form Introduction
     */
    
    public LoadingScreen() {
        initComponents();
        setIcon();
    }
    
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gamelogo.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        LoadingBar = new javax.swing.JProgressBar();
        LoadingPercentage = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Truth Table Quiz");
        setBackground(new java.awt.Color(122, 215, 240));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        setForeground(java.awt.Color.cyan);
        setLocation(new java.awt.Point(500, 250));
        setName("TruthTable"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(38, 36, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingBar.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 350, 40));

        LoadingPercentage.setBackground(new java.awt.Color(122, 214, 242));
        LoadingPercentage.setFont(new java.awt.Font("Æ Systematic TT (BRK)", 0, 24)); // NOI18N
        LoadingPercentage.setForeground(new java.awt.Color(255, 255, 255));
        LoadingPercentage.setText("0%");
        jPanel1.add(LoadingPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 340, -1, -1));

        Title.setBackground(new java.awt.Color(122, 215, 240));
        Title.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/logoresized.png"))); // NOI18N
        Title.setToolTipText("");
        Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Title.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 220, 220));

        jLabel1.setFont(new java.awt.Font("Æ Systematic TT (BRK)", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DEVELOPED BY:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 400));

        setSize(new java.awt.Dimension(370, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        LoadingScreen intro = new LoadingScreen();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                intro.setVisible(true);
            }
        });
        Title home = new Title();
        try{
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(40);
                intro.LoadingBar.setValue(i);
                intro.LoadingPercentage.setText(Integer.toString(i)+"%");
            }
        }
        catch(Exception e){
            
        }
        new LoadingScreen().setVisible(false);
        home.setVisible(true);
        intro.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JProgressBar LoadingBar;
    javax.swing.JLabel LoadingPercentage;
    javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}

