/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TruthTable;

import java.awt.Toolkit;

/**
 *
 * @author asus
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();      
        setIcon();
    }

    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gamelogo.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        startbtn = new javax.swing.JButton();
        tutorialbtn = new javax.swing.JButton();
        Generator = new javax.swing.JButton();
        scorebtn1 = new javax.swing.JButton();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Truth Runes");
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(1336, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1336, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startbtn.setFont(new java.awt.Font("Æ Systematic TT (BRK)", 0, 24)); // NOI18N
        startbtn.setText("START");
        startbtn.setPreferredSize(new java.awt.Dimension(180, 80));
        startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtnActionPerformed(evt);
            }
        });
        jPanel1.add(startbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 180, 80));

        tutorialbtn.setFont(new java.awt.Font("Æ Systematic TT (BRK)", 0, 24)); // NOI18N
        tutorialbtn.setText("TUTORIAL");
        tutorialbtn.setMaximumSize(new java.awt.Dimension(93, 23));
        tutorialbtn.setMinimumSize(new java.awt.Dimension(93, 23));
        tutorialbtn.setPreferredSize(new java.awt.Dimension(180, 80));
        tutorialbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialbtnActionPerformed(evt);
            }
        });
        jPanel1.add(tutorialbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, -1));

        Generator.setFont(new java.awt.Font("Æ Systematic TT (BRK)", 0, 24)); // NOI18N
        Generator.setText("GENERATOR");
        Generator.setPreferredSize(new java.awt.Dimension(180, 80));
        Generator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratorActionPerformed(evt);
            }
        });
        jPanel1.add(Generator, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        scorebtn1.setFont(new java.awt.Font("Æ Systematic TT (BRK)", 0, 24)); // NOI18N
        scorebtn1.setText("SCORES");
        scorebtn1.setPreferredSize(new java.awt.Dimension(180, 80));
        scorebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scorebtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(scorebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 510, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, -100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Alkhemikal", 0, 210)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Truth Runes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 1030, 230));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TruthTable/bg.gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setMaximumSize(new java.awt.Dimension(1336, 720));
        jLabel6.setMinimumSize(new java.awt.Dimension(1336, 720));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, 1700, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1336, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtnActionPerformed
        new Difficulty().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_startbtnActionPerformed

    private void GeneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratorActionPerformed
        new Generator().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_GeneratorActionPerformed

    private void tutorialbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialbtnActionPerformed
        // TODO add your handling code here:
        new Tutorial().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_tutorialbtnActionPerformed

    private void scorebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scorebtn1ActionPerformed
        new Scores().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_scorebtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton Generator;
    javax.swing.JButton scorebtn1;
    javax.swing.JButton startbtn;
    javax.swing.JButton tutorialbtn;
    // End of variables declaration//GEN-END:variables
}

